### ISSUE TITLE
"Sane" error reporting wrt. to feedback-files

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/staffeli_nt#18]
When a grade.yml file is formatted incorrectly and run through `upload.py`, staffeli_nt currently crashes with an uncaught exception. 
There is no direct info on what caused the crash and chasing down the syntax-mistake in ~20 .yml files is tedious. 

I propose a bit of error-handling. Catching exceptions from parsing and printing the path of the culprit-file would be a great start.

**Comment by kfl** [comment]
With PR #28 merged, I think that the error reporting is no longer piss-poor. Maybe it is even "sane".

@madsobitsoe is it OK that we close this issue?

**Comment by madsobitsoe** [comment]
Yes, very ok!
