### ISSUE TITLE
Add support for fetching assignments based on a list of kuid's

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/staffeli_nt#22]
We have support for fetching all assignments, and assignments based on sections. 
In PoP21E we have extra TA's who only do grading, and thus will split the assignments arbitrarily each week.

It would be valuable to have a single file with all TA's and associated assignment submissions (by kuid), which staffeli could parse, allowing each TA to fetch only "their" assignments. 

I imagine a workflow resembling:
1) One unlucky TA (me :'( ) will fetch all submissions for a given assignment
2) The unlucky TA will manually designate assignments to TA's - to even out the workload
3) The unlucky TA will supply this file to the rest of the TA's
4) The lucky TA's will run `./download.py --selected-submissions COURSEID TEMPLATE ASSDIR`
5) The lucky TA's will be presented with a menu, can select their name and will get their designated submissions

I imagine a file with the format:

```
TA: Mads
kuid1
kuid2
kuid3
TA: Jacob
kuid4
kuid5
kuid6
```

I am very open to suggestions, improvements and "This is a terrible idea Mads".

**Comment by kfl** [comment]
Can this be closed now that the PR is merged?

**Comment by madsobitsoe** [comment]
Yes, indeed it can!
