### ISSUE TITLE
Add support for excluding internal points from feedback files

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/staffeli_nt#23]
(I am unsure if this is already possible) 

Jon Sporring does not want the "internal points" to be present in the feedback files the students receive, and only have "Godkendt" or "Genaflevering" (+ feedback). 
It should be a simple addition/change to `upload.py`. 

I think extending the template-format with an optional field, the same was as the `passing-points` field is the "best" way to introduce this. There's already a lot of command line arguments.

**Comment by kfl** [comment]
Can this be closed now that the PR is closed?

**Comment by madsobitsoe** [comment]
Yes, indeed it can!
