### ISSUE TITLE
download.py fungerer ikke med --select-ta hvis en TA mangler opgaver.

### ISSUE THREAD

**Issue by aske0778** [kfl/staffeli_nt#32]
Som beskrevet ovenover så kan man ikke downloade opgaver via en ta_list.yml hvis der er en TA inkluderet der ikke har fået tildelt opgaver. Jeg fik det til at fungere ved at slette den TA fra listen.

**Comment by madsobitsoe** [comment]
I believe #47 solved this, and the issue can be closed.
