### ISSUE TITLE
Make stafffeli run all submissions through onlineTA

### ISSUE THREAD

**Issue by Spatenheinz** [kfl/staffeli_nt#34]
The title says it all. I am working on a feature that will allow staffeli to run all submissions through onlineTA,
My idea is to add a field in the yaml file as such:

onlineTA: url-to-the-subinstance-of-onlineta/assignment

**Comment by kfl** [comment]
I'm all for making `staffeli_nt` more useful (so don't let this comment stop you).

However, extending the download script like this will worsen #4 if possibe, I'd prefer that the template yaml file grew a field called `post-download` (or something like that) that contained some python code that you'd like to run after each download.

Something like:

```yaml
post-download: |
    import zipfile
    with zipfile.ZipFile("code.zip", 'r') as zip_ref:
         zip_ref.extractall("unpacked")
```

We might as well take full advantage of python having an [`eval` function](https://docs.python.org/3/library/functions.html#eval).

But as I said, don't let my pipe dreams hold you back.
