### ISSUE TITLE
Add support for course sections in download

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/staffeli_nt#8]
The option to only download submissions for a specific course section would be nice. 

The Canvas API seems to support this - at least in a hacky way if not directly. 
https://canvas.instructure.com/doc/api/sections.html#method.sections.index

The canvasapi for python has support for retrieving section(s). It is unclear to me if it retrieves the associated userid's.
https://github.com/ucfopen/canvasapi/blob/develop/canvasapi/course.py#L1962

**Comment by kfl** [comment]
Download now has some (undocumented) support for sections, support in upload is still missing.

**Comment by madsobitsoe** [comment]
This works almost perfectly! 
Submissions from students who have switched to another course section are included in the download. 

(This might be due to the way we handle section reassignments on PoP, through Absalon's webinterface).
If a student has switched course section, absalon doesn't allow us to delete the enrollment in the original course section, but only to "conclude" the enrollment. 

As far as I can tell, this should work, but does not (with my limited trial-and-error testing).
```
submissions = section.get_multiple_submissions(assignment_ids=[assignment.id], student_ids=['all'], enrollment_state='active')
```
A hacky fix could be to make two API calls: 
1) get a list of student ids, of students in the section with enrollment_status=='active'. 
2) Download the submissions
I have implemented this fix in my fork and will make a pull-request.

**Comment by kfl** [comment]
Upload also support sections now

**Comment by kfl** [comment]
For upload I'm not sure what is the right way to handle students who change sections. But the upload script should give a warning if it detects it.

**Comment by madsobitsoe** [comment]
I will let you know what quirks I find after I test it out tonight. 
I think getting a list of students that same was as I do in download.py #10  would work. (line 134 in upload.py)

**Comment by kfl** [comment]
@madsobitsoe does the new version work around the problem with `"concluded"` students?

**Comment by madsobitsoe** [comment]
Yes, it only downloads submission from students with active enrollments.

**Comment by madsobitsoe** [comment]
I think the addition of sections might have broken download of all submissions. 

I got this error when trying to download all submissions for an assignment. 

```
Traceback (most recent call last):
  File "../../staffeli_nt/staffeli_nt/download.py", line 200, in <module>
    assignment=MetaAssignment(assignment.id, assignment.name, section=section.id),
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by kfl** [comment]
Every thing should work now.
